apiVersion: batch/v1
kind: Job
metadata:
  name: pyspark-runner
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: pyspark-runner
        image: pyspark-runner
        imagePullPolicy: IfNotPresent  # important needed when testing on local env
        command: ["python",  "spark_trending.py", "--fileName=sample.json"]
        resources: {}
        workingDir: /home/Scripts
        env:
        - name: SPARK_MASTER
          value: "spark://{{ template "master-fullname" . }}:{{ .Values.Master.ServicePort }}"
      restartPolicy: Never
status: {}
